### ISSUE TITLE
Visualizing Results

### ISSUE THREAD

**Issue by Iron-Stark** [vik-goel/MOREL#1]
Hi,

I was trying to retrain this model locally, while the model trains successfully and I am able to store the index, meta and data files, I am unable to figure out how to visualize the results. I was trying to use the following command to plot the results:

python -m baselines.run --alg=a2c --env=PongNoFrameskip-v4 --num_timesteps=0 --load_path=my-model-72000.data-00000-of-00001 --play

I put the index, meta and data files generated in the root folder along with PongNoFrameskip-v4 folder to avoid path issues.

The issue is that baselines folder does not have any run.py file. I tried copying the openAi baseline run.py file here but that doesn't seem to work. Can you please help me with how to visuzalize the results of the trained model?

**Comment by JamesonWeng** [comment]
Hello! Usually we use tensorboard to visualize results, as most of our scripts will create a logs directory that records a bunch of training metrics. There's also some code (for example in a2c.py) that saves videos of the model during training. It currently syncs to aws, but you can probably change it to just save locally. Hope this helps :)

**Comment by Iron-Stark** [comment]
Thanks a lot for your reply. I will take a look at it.
