### ISSUE TITLE
Reproducing Object Masks

### ISSUE THREAD

**Issue by BlazingFire** [vik-goel/MOREL#3]
Hi, I was trying to plot generated objected masks during training but I am unable to get similar results as in paper, can you help me in correcting this issue?
My results look like this :
![1 (copy)_sigmoid](https://user-images.githubusercontent.com/10053970/83250689-2a177b80-a1c6-11ea-840d-36cf64cf4bb4.png)
I am using this command to run code :  python train_network.py  ../hparams/env=Breakout,algorithm=a2c.json

Thank you

**Comment by vik-goel** [comment]
Hi Abhishek! The object masks can be visualized using tensorboard (see log_image in sfmnet.py). For example, on Breakout the object masks looked like this: [https://www.youtube.com/watch?v=k1wlsR55wpI&list=PLhh84l5EzbN4kPAkieJ6Il2l8EC4iw12W&index=17&t=0s](url).
